server:
  port: 9067

spring:
  elasticsearch:
    rest:
      uris: http://192.168.1.100:9200
  data:
    elasticsearch:
      repositories:
        enabled: true
      cluster-nodes: 192.168.1.100:9300
      cluster-name: elasticsearch

